### ISSUE TITLE
ActiveRecord::Relation#inspect doesn't return string

### ISSUE THREAD

**Issue by altV** [k-tsj/power_assert#12]
Hello, Kazuki,

ActiveRecord::Relation#inspect doesn't return instance of String, rather it returns an Array,
which makes non-instantiated Rails collections uninspectable.

(and also makes pry-power_assert not compatible with Rails as well)

**Comment by k-tsj** [comment]
Can you give me steps to reproduce?

As far as I can see, ActiveRecord::Relation#inspect returns only String.
https://github.com/rails/rails/blob/v4.2.0/activerecord/lib/active_record/relation.rb#L628

**Comment by k-tsj** [comment]
I'm going to close this. Please reopen if you need.
