### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by wwood** [k-tsj/power_assert#15]
Hi there,

As you have already fixed in master, the released power_assert gem has a test failure with Ruby 2.3. Since the GNU Guix package manager runs tests on the gems packaged, power_assert is now no longer able to be built.

Would you mind releasing a new version of power_assert please?

Props on finding and fixing the bug so fast by the way.
Thanks,
ben

**Comment by k-tsj** [comment]
I've released power_assert 0.2.7.

**Comment by wwood** [comment]
Excellent, thanks.
