### ISSUE TITLE
power_assert breaks Hash

### ISSUE THREAD

**Issue by rovf** [k-tsj/power_assert#19]
Consider the following program:

```ruby
#!/usr/bin/env ruby
$VERBOSE = true
require 'power_assert/enable_tracepoint_events'
class Hash
  STDERR.puts method_defined?(:<<)
  alias << merge!
  STDERR.puts method_defined?(:<<)
end
```
n older Ruby versions (1.9.3, 2.3.3), the output of this program was:

**
false
true
**

In Ruby 2.4.1, the output is

**
false
~/work/stash/vp5/src/test/test_xx.rb:6: warning: method redefined; discarding old <<
true
**

Please note:

1. The warning occurs, even though method_defined? tells us that no << method is in Hash.
2. The warning disappears, when we do **not** require power_assert
3. Changing the offending line to *alias :<< :merge!* does not make any difference

(Bug originally reported at https://bugs.ruby-lang.org/issues/13817, where it was found to be a bug in power_assert)

**Comment by k-tsj** [comment]
As fixed at ruby/ruby@0db193f98d97d235e7628815b2ba64dc530be2e6, this is a bug of ruby.

I added workaround to avoid it, so please try it.
