### ISSUE TITLE
Syntax error for a statement with multiple lines

### ISSUE THREAD

**Issue by piroor** [k-tsj/power_assert#20]
For readability I sometimes want to write a code like:

```ruby
assert do
  # folded because it is too long for one line
  foo.bar?(a: aaaaaaaaaaaaaaaaaaaaaa, 
           b: bbbbbbbbbbbbbbbbbbbbbb,
           c: ccccccccccccccccccccccccc)
end
```

However `power_assert` reports a syntax error for such cases, because it just parses codes per lines. Thus, I hope that this "issue" to be fixed in these two steps:

 1. Just add a note for the known limitation to the README.md.
 2. Add support for such cases, and remove the note for the fixed problem.

How about that?

----

うまく伝えられているか自信がないので日本語でも書きます。
冒頭の例のように、1行が長くなりすぎる時に読みやすさのため途中に改行を入れるということはよくあると思います。しかしながら、現在の`power_assert`は行単位でコードをパースしているため、このようなコードがあると文法エラーになってしまうという問題があります。そこで、以下の2段階で解決していくのはどうかと考えています。

 1. まずREADME.mdに、既知の制限事項として注意書きを追加する。
 2. 複数行に渡る文への対応を進め、作業が完了した時点でその注意書きを削除する。

2は実現可能なのかどうかまだ判断がつかないため、最悪の場合1だけに留まる可能性もあると考えておりますが、何も注意書きがないよりは、ユーザーがいざ同じ問題に遭遇した時に戸惑わずに済むのではないかと思います。
いかがでしょうか？
（この方法で進めてよいということであれば、こちらで作業しPRするつもりでおります。）

**Comment by k-tsj** [comment]
I agree with your proposal.
Can you send me a PR?

---

```power_assert```には式が1行で書かれていなければいけないということ以外にも

* 式にメソッド呼び出しが含まれていなければならない
* アクセサメソッド、```method_missing```、```super```などの戻り値が表示されない
* 式に分岐が含まれていると戻り値が表示されないことがある

など、いくつか制約があります。
いつかまとめないといけないなと思ってはいたので、PRは大歓迎です。

その他、細かいところを補足しておくと

* Ruby 2.4以降であればsyntax errorは表示されなくなります。(表示されないだけでパースに失敗していることに変わりはありませんが)
* 複数行対応は、Ruby本体にProcのASTを取得できるAPIを追加するか、```TracePoint```にイベント発生時の桁情報を取得するAPIを追加するかといったことが必要かと思っています。どちらにせよ先は長そうです。

**Comment by piroor** [comment]
ありがとうございます！ひとまずREADMEの変更のみでPRを作成してみました。
