### ISSUE TITLE
Is it possible to correspond to standard input code?

### ISSUE THREAD

**Issue by akicho8** [k-tsj/power_assert#28]
I also want to use power_assert conveniently even in xmpfilter of rcodetools.

```shell
% cat a.rb
require "power_p"
p { 1 == 2 }
```

```shell
% ruby a.rb
p { 1 == 2 }
      |
      false
```

```shell
% xmpfilter a.rb
require "power_p"
p { 1 == 2 }
# >>
```

I am very happy if I can do this.

### Steps to reproduce

```shell
echo 'p { 1 == 2 }' | ruby -r power_p
```

### Expected behavior

```shell
p { 1 == 2 }
      |
      false
```

### Actual behavior

```shell

```

It does not display anything

### System configuration

power_assert-1.1.1
power_p-1.0.0
rcodetools-0.8.5.0
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin16]

**Comment by k-tsj** [comment]
I understand your request, but it is very difficult because CRuby doesn't provide API to get source code given by STDIN, command line argument, etc.
If you really want it, please create a feature request at [CRuby's BTS](https://bugs.ruby-lang.org/projects/ruby-trunk/issues).
