### ISSUE TITLE
power_assert 0.2.2 tests fail with ruby 1.9

### ISSUE THREAD

**Issue by graaff** [k-tsj/power_assert#8]
With ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-linux] I'm seeing the following test failure.

```

/usr/lib64/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require': /var/tmp/portage/dev-ruby/power_assert-0.2.2/work/ruby19/power_assert-0.2.2/lib/power_assert.rb:25: syntax error, unexpected tLABEL (SyntaxError)
...oc_or_source, assertion_method: nil, source_binding: TOPLEVE...
...                               ^
/var/tmp/portage/dev-ruby/power_assert-0.2.2/work/ruby19/power_assert-0.2.2/lib/power_assert.rb:25: Can't assign to nil
..._source, assertion_method: nil, source_binding: TOPLEVEL_BIN...
...                               ^
/var/tmp/portage/dev-ruby/power_assert-0.2.2/work/ruby19/power_assert-0.2.2/lib/power_assert.rb:314: syntax error, unexpected keyword_end, expecting $end
	from /usr/lib64/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /var/tmp/portage/dev-ruby/power_assert-0.2.2/work/ruby19/power_assert-0.2.2/test/test_power_assert.rb:2:in `<top (required)>'
	from /usr/lib64/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/lib64/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/lib64/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:15:in `block in <main>'
	from /usr/lib64/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:4:in `select'
	from /usr/lib64/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:4:in `<main>'
```

I noticed that ruby 1.9 is not listed in your travis setup, so perhaps you no longer want to support that version. In that case it is probably best to specify that in the gemspec.

**Comment by k-tsj** [comment]
Since test-unit depends on power_assert, if we set required_ruby_version in the gemspec
1.9 users will not be able to use test-unit. Instead, I added requirement section in README.

Of course, removing explicit dependency on power_assert is a one way.
But @kou(a maintainer of test-unit) recommends to use Power Assert for predicate method testing,
so I guess it will not happen.

**Comment by graaff** [comment]
I've filled this issue since I'm trying to package test-unit 3.x for Gentoo Linux and we still have plenty of packages that (also) install ruby 1.9 code.

Based on your explanation I think we will change our test-unit 3.x package to remove the power_assert dependency from the installed gemspec for ruby 1.9 only. That way things will remain compatible with test-unit 2.x for ruby 1.9 and for ruby 2.0 and newer power_assert will be available as expected.
Thanks for you feedback, and I guess this issue can be closed?

**Comment by kou** [comment]
I think that you don't need to anything for test-unit gem. Because test-unit gem ignores `SyntaxError` on loading power_assert gem: https://github.com/test-unit/test-unit/blob/master/lib/test/unit/assertions.rb#L13

If you use test-unit on Ruby 1.9, you don't see power_assert error.

**Comment by graaff** [comment]
It is still listed in the gemspec so anything that depends on test-unit will still try to pull it in. But in Gentoo we cannot install power_assert for ruby 1.9 because our users can optionally run tests for all packages and these would fail for power_assert with ruby 1.9.
I guess we could avoid running the tests for power_assert with ruby 1.9 specifically and install the broken code, but I would rather not install code that is known to be broken. This may also cause issues when other packages start to depend on power_assert.

Finally, we are actively working on the ruby 1.9 deprecation, so this situation will only be relevant for a few months at the most.

**Comment by k-tsj** [comment]
Thanks, I understand your situation.
