### ISSUE TITLE
grape gem との組み合わせで Segmentation fault

### ISSUE THREAD

**Issue by akicho8** [k-tsj/power_assert#9]
不具合報告です。
rails + grape + test-unit-rails の組み合わせで Segmentation fault になる場合がありました。
エラーログ → https://raw.githubusercontent.com/akicho8/power_assert_with_grape_app/master/error.txt
power_assert のバージョン 0.2.2 と github の master で、同様にエラーになりました。
試しに power_assert のバージョンを 0.1.3 に固定するとエラーは起きませんでした。

こちらに github の master を参照してエラーを再現する最小構成のRailsアプリを置きました。
https://github.com/akicho8/power_assert_with_grape_app

**Comment by k-tsj** [comment]
Rubyのバグでした。
https://bugs.ruby-lang.org/issues/10885

次のパッチバージョンで修正されるはずです。

**Comment by akicho8** [comment]
不安定な test-unit を無理して使わず普通に rspec で行こうみたいなまわりの空気に、test-unit使いたい派としては苦しい立場にあったので、原因がわかって本当によかったです。
対応ありがとうございました。

**Comment by akicho8** [comment]
ruby 2.2.1p85 で正しく動作したのを確認しました:smile:

**Comment by k-tsj** [comment]
報告ありがとうございます。
